
services:
  - type: web
    name: th-eletricista
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
    buildCommand: docker build -t th-eletricista .
    startCommand: docker run -p 8080:8080 th-eletricista
